blindsidenetworks-ps/moodle-mod_bigbluebuttonbn

lang/en/bigbluebuttonbn.php
lib.php
locallib.php
view.php

Currently is very hard to correctly translate email notifications to some other languages. The problem is that some languages has other order of words, than english, so creating message by simple contactenation of lang strings in fixed order is incorrect. Correct is to use get_string substtutions, so that translator may be able to shange order of words and substitutions. This commit fixes this problem

Fixing lang strings to improve translations

---

locallib.php

When line 575 use a 'AND' operator, a user with multiple roles in the current context get 0 roles back since the criteria is not met. I think the intended result is met with the operator 'OR', so we get several roles back.

Change operator "AND" to "OR" in order to fetch several roles

---

backup/moodle2/backup_bigbluebuttonbn_stepslib.php
bbb_broker.php
bbb_view.php
classes/locallib/bigbluebutton.php
classes/locallib/config.php
classes/settings/renderer.php
config-dist.php
db/install.xml
db/upgrade.php
lang/en/bigbluebuttonbn.php
locallib.php
mod_form.php
settings.php
version.php
view.php

As per your previous request, i did this pull request for letting you evaluate my changes for coding this new feature. I tried to follow your coding philosophy, so most of the changes to the code were done for a "correct" integration of the new setting, enabling/disabling it and it's default.
The semantic section is around the join API, were i added the joinViaHTML5 with value true if requested a define time of each single room.
The BBB server should be configured to serve the HTML5 client, but without forcing it. If the HTML5client is not installed, this option it's simply ignored.

CONTRIB-7413: New feature: choose between Flash/HTML5 Web Client in each room

---

classes/locallib/notifier.php

Hi!
It seems that a minor bug is preventing the notification messages to be send in HTML. What's rather odd is that this is fixed in `master`.
Well, here it is. Thanks for your work.
Regards.

Fix notification messages send in FOMAT_MOODLE instead of FORMAT_HTML.

---

lib.php

Hi everyone,
We are getting this unit test failure on v2.2 stable. Could you please help fix this? 
I've created a pull request to require the locallib that's needed for this function call
`bigbluebuttonbn_random_password()`
https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/issues/127
Thanks

CONTRIB-7875: Fix Call to undefined function bigbluebuttonbn_random_password()

---

classes/privacy/provider.php

I added the core_userlist_provider which was already implemented in the class itself (but did not declare the interface, this is what was failing the test).
I reformatted the declaration as I saw an example in mod_forum which was more explicit about the way it inherit/implement privacy.

CONTRIB-7983: BigblueButtonBN module fails core privacy provider test case

---

locallib.php
mod_form.php

In the participant menu of the activity, make sure that we can only see the users that are in the same group if it is the constraint set (#173)
If we choose separate groups and have no right to see other users, then we cannot see other group as a teacher or any user part of a group
* Add unit/behat test to test this specific feature
* Make sure that we just get the right group mode (check the forced course group flag) in the activity view page

CONTRIB-7972, CONTRIB-7973

---

locallib.php

Make sure that a user who cannot see user in a different group can just see a sublist of users when looking at the participant list. This fixes the issue when we add a new instance of the activity, as we previously fixed the issue in edit mode.

CONTRIB-7972 Fix issue with group mode when a new activity is added

---

classes/output/index.php

When looking a the room list as a table the End Session button did not work (the session was still running). 
Note that we have to add the "activities block" in order to see all activities in a course and access the page.

CONTRIB-7895: End session does not work on the room list

---

locallib.php

As follow up for CONTRIB-7970, we had some issue with joining a conference due to missing (recursive) dependencies in the locallib.php (since they were not included globally in lib.php).

CONTRIB-7997: remove some global dependencies on core libraries in the locallib

---

locallib.php
tests/behat/recordings_import.feature
viewlib.php

On the BigblueButtonBN activity page, we would need to remove the Meeting column from the recording table/list.
This changes the following on the table:
* Remove the Meeting column from the recording table
* Rename the column "Recording" into "Name"

CONTRIB-7703 Meeting name is not required in the recording list

---

locallib.php

If a role has been deleted in the list of Moodle roles, then all the subsequent roles will not appear in the bigbluebuttonbn list of participant / roles.

CONTRIB-7966 : Make sure that the Moderator by default setting take into account all roles

---

tests/behat/recordings_import.feature
viewlib.php

This was due to the type of recording and the features enabled in this type. For BIGBLUEBUTTONBN_TYPE_RECORDING_ONLY, the feature ''showroom' in the was not enabled. Down the line, we check for this feature and if it is enabled, we filter it accordingly.
There was a specific branch for testing this feature through behat but this is not ready yet.

CONTRIB-7961 When importing records in a record only BBB activity, then is show all the recordings

---

db/access.php

Causes totara unit test to fail. 
`vendor/bin/phpunit --colors totara_core_access_testcase totara/core/tests/access_test.php`

Remove CAP_PREVENT

---

locallib.php

Bug fix for large lists. The link is written as "#". The page goes to the top when the link is clicked. But the confirm box remains at the bottom of the page and is not clicked.

CONTRIB-8045 Bug fix for large lists

---

locallib.php

It looks like one of the method names wasn't switched to snake_case.

GIT-XX: small fix for method name

---

lib.php

Before this patch, the bigbluebuttonbn_print_overview_element() function, which is called from bigbluebuttonbn_print_overview() which is deprecated since Moodle 3.8 but which is still called on previous Moodle core versions and from old-style Moodle Dashboard blocks, didn't check if $bigbluebuttonbn->closingtime is defined in the particular BBB activity instance or not.
As a result, users saw this line for BBB activity instances with a openingtime set but without a closingtime set.
Ends: Thursday, 1 January 1970, 1:00 AM
This patch fixes this flaw in a way that it only shows the closingtime in addition to the openingtime if the closingtime is really set in the BBB activity instance.

CONTRIB-8158: Don't show the closingtime on the Dashboard if it isn't set in the activity instance

---

locallib.php

If activity in group mode, then the admin or moderators should be able to see all recordings regardless of the activity group mode.
The issue at hand was that bigbluebuttonbn_include_recording_table_row was hiding the row if the BBB session has a group mode set.
This patch will resolve the issue for admins, but the issue will still likely to be there for other users. The check made in this function are somewhat redundant with the ones made in bigbluebuttonbn_get_recording_table, so we might have to go further here and refactor at least the bigbluebuttonbn_get_recording_data_row so it does not add further checkings (call to bigbluebuttonbn_include_recording_table_row).

CONTRIB-8038 mod_bigbluebutton: Recordings should be visible to admins

---

lang/en/bigbluebuttonbn.php

Remove leading line break. The information regarding the audio-bridge 
are not accurate anymore and have been removed.

Changes to mod_form_field_welcome_default

---

locallib.php
mod_form.php

* Completion tracking was not run whenever completionattendance was not set
* The form should use advcheckboxes instead of checkboxes (it was not possible to unselect a completion option from the module edit form)

CONTRIB-7918 mod_bigbluebuttonbn: Fix issue with completion tracking

---

tests/lib_test.php
tests/locallib_test.php
tests/privacy_provider_test.php
tests/recordings_test.php

This is backwards compatible with PHPUnit 7.x used in Moodle 3.9.

Make setUp() and tearDown() signatures compatible with PHPUnit 8.5 in Moodle 3.10

---

lang/en/bigbluebuttonbn.php
mod_form.php

**- changes welcome message from PARAM_TEXT to PARAM_CLEANHTML**
The actual form field's data type for the welcome message is PARAM_TEXT. HTML tags are sanitized and have no effect once we join the room. This commit changes the data type to PARAM_CLEANHTML so that tags are interpreted.
**- completes and escapes authorized html tags in helper**
HTML tags in the welcome field's help were interpreted and did not appear as such on screen. They've been escaped so that users can read them. The string has also been completed with two tags : &lt;br /> and &lt;u>&lt;/u>

Fixes welcome message sanitizing

---

bbb_view.php
brokerlib.php
classes/external.php
classes/local/bigbluebutton.php
classes/local/config.php
classes/local/helpers/instance.php
classes/local/helpers/reset.php
classes/local/mobileview.php
classes/local/notifier.php
classes/output/import_view.php
classes/output/mobile.php
classes/task/send_notification.php
import_view.php
lib.php
locallib.php
mod_form.php
settings.php
view.php
viewlib.php

Fix use of Level 2 Namespace
* Move bigbluebutton, config, mobileview and notifier class into the  local namespace
This merge has to happen after CONTRIB-8400 and CONTRIB-8392 as it depends on some changes made in these tickets.

CONTRIB-8393: Fix use of invalid Level 2 Namespaces 

---

bbb_ajax.php

Declare that calls to bbb_ajax.php only require a read-only session,
which reduces session lock contention on pages calling making AJAX
requests to this endpoint.
See-also: [MDL-58018](https://tracker.moodle.org/browse/MDL-58018)

bbb_ajax.php: declare READ_ONLY_SESSION

---

classes/external/meeting_info.php
templates/room_view.mustache

The new implementation show the End meeting button even if the user is not a moderator.
A click on the button is followed up with an error message but the button in fact should be completely hidden.

CONTRIB-8536: non moderator should not see "End meeting" button

---

classes/external/get_recordings.php
classes/external/meeting_info.php

When a date was set on the BBB activity, the recording API was returning in this case a status of 'not_started' which was not compatible with the declared API value.
For this to show up the opening time should be set to a later time (i.e. currenttime + XXX).
I also corrected another warning due to the presentation not defined and checked that the behaviour when setting the date/time is right:
- We check waitformoderator
- Set a date
- And if we are not a moderator nor an admin we should not be able to see the join button

CONTRIB-8528: Error when viewing an activity with a set date

---

lib.php

Activity is always visible in the calendar:
- Hide the activity if its status is "closed"/ended

CONTRIB-8461 - Activity is always visible in the calendar

---

lib.php

* The calendar view was spamming Bigblue button server in case we had
many events
* Use cached version if available.
* if not do not display the actionable button is only displayed if we
have enough information

CONTRIB-8419: Spamming BBB Server on calendar dashboard view

---

classes/locallib/bigbluebutton.php

When the Welcome message is removed from the Room, the one defined by
the default string from translations is used. It should be the value
defined in the welcome_default setting

CONTRIB-8573: Fix default welcome message

---

classes/locallib/bigbluebutton.php
classes/locallib/config.php
lang/en/bigbluebuttonbn.php
locallib.php
mod_form.php

* Force welcome message if the new setting (welcome_editable) is not set
* If not allow to edit the welcome message in each activity

CONTRIB-8574: Add option to allow teachers to edit the welcome message

---

locallib.php

* Check the the setting recordingready_enabled is still enabled when
receiving the event from Bigbluebutton

CONTRIB-8591: Disable notification on recording ready callback

---

.github/workflows/ci.yml
classes/test/testcase_helper.php
tests/behat/behat_mod_bigbluebuttonbn.php
tests/behat/recordings.feature
tests/behat/recordings_import.feature
tests/completion_test.php
tests/coverage.php
tests/instance_test.php
tests/lib_test.php
tests/local/bigbluebutton/recordings/recording_data_test.php
tests/local/bigbluebutton/recordings/recording_helper_test.php
tests/local/bigbluebutton/recordings/recording_test.php
tests/local/helpers/files_test.php
tests/local/helpers/mod_helper_test.php
tests/local/helpers/reset_test.php
tests/local/helpers/roles_test.php
tests/local/notifier_test.php
tests/logger_test.php
tests/privacy/provider_test.php

These changes include:
* switch back to my mock server image to support parallel behat runs
* Fix GHA to allow the mock container to access the behat host
* Fix behat tests to work with new navigation on moodle master branch for 4.0
* Ensure that remote tests are skipped if the remote server is not defined
* Fix code coverage generation to only report lines which are intentionally tested
Suggest picking these commits without merge commit.

A variety of fixes for PHPUnit, Behat, and GHA as part of CONTRIB-8660

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Split jobs by jobs which require a Moodle install vs those which don't.
This will increase the total number of jobs, and mean that tasks like
linting, mess detection, etc. are much faster to finish.

CONTRIB-8660: Split GHA jobs

---

classes/instance.php
classes/meeting.php
lib.php
tests/instance_test.php

It appears we have a few bugs. I don't know the solution - these need
your input:
* allow_start_stop_recording when the recording is started at meeting
creation does not behave as I would expect.
* is_room_available duplicates behaviour of is_currently_open.
Personally I prefer is_currently_open because it is clearer to read
and understand.

CONTRIB-8660: Add more tests for instance

---

classes/local/proxy/proxy_base.php
tests/behat/add_instance.feature
tests/behat/behat_mod_bigbluebuttonbn.php
tests/behat/end_meeting.feature
tests/behat/group_mode.feature
tests/behat/installed.feature
tests/behat/join_meeting.feature
tests/behat/meeting_roles.feature
tests/behat/recordings.feature
tests/behat/recordings_import.feature
tests/behat/start_meeting.feature

A long-standing behat bug prevents tests from being marked as skipped in
a BeforeScenario (https://github.com/Behat/Behat/pull/1214) without
causing the entire suite to be re-run.
This fix adds a step to the background of every feature to allow it to
check that setup is complete.

CONTRIB-8660: Fix behat skip tests

---

classes/settings.php

Such that when the config setting is forced, MDL-63734 will prevent the secret from being observed in the admin settings page.
Fixes #460

Change shared_secret to be a masked config password admin setting

---

classes/meeting.php

There is some difficulty with URL encoding in various params.

CONTRIB-8674: Do not use a moodle_url when generating the join URL

---

mod_form.php

Some class name references do not use FQ class names in BBB activity form. When referenced by php interpreter Moodle crashes with a fatal error that does not reveal primary cause of problem.
Additionally a few minor changes were made with phpdoc and unreachable return statements.

Fix fatal errors when referencing missing class names

---

classes/logger.php
classes/meeting.php
tests/external/view_bigbluebuttonbn_test.php

* The view_bigbluebuttonbn_test testcase were wrong and the require_login was never called (this on postgres + mysql) because we  were looking at the cmid instead of the instance id. However on MSSQL as cmid = instanceid, the test failed.
* Fixed the test so they test the adequate workflow (we need to be logged and access the activity to use the view_bigbluebuttonbn API)
* Remove the "Create" event log

CONTRIB-8694: Multiple fixes

---

classes/settings.php
db/caches.php

It is much better to use cache invalidation/purging than creating the caches and purging them manually. The code which invalidates the cache should not need to know which caches it has to invalidate - the caches are a function of the code using them, not unrelated code.

CONTRIB-8660: Use events for cache purging

---

classes/meeting.php
templates/room_view.mustache
tests/meeting_test.php

* Fix room template to reflect information returned by get_meeting_info
* Fix number of viewer (total participant - moderators)
* Fix and add further test related to participant count. The number of participants/viewers counted by the mock server was different from the one counted by the real server as it included moderators + participants.

MDL-70658: Fix room information display

---

mod_form.php

* The fix applied previously for mod_form and completionattendancegroup,
completionengagementgroup was throwing an exception when
bigbluebuttonbn_meetingevents_enabled is disabled

MDL-70658: Fix issue with completion groups when meetingevents disabled

---

classes/instance.php
classes/local/bigbluebutton/recordings/recording_data.php

* When Show imported links only is enabled in activity or config, only imported recordings will appear
* Logic for activity/default overrides implemented

CONTRIB-8955: Fix show imported links only logic

---

bbb_broker.php
classes/broker.php

Use JWT library classes included in Moodle 311 and not the ones in 4.0+

CONTRIB-9044: Fix JWT library use

---

.github/workflows/ci-moodle3.10.yml
.github/workflows/ci-moodle3.11.yml
.github/workflows/ci-moodle3.4.yml
.github/workflows/ci-moodle3.5.yml
.github/workflows/ci-moodle3.6.yml
.github/workflows/ci-moodle3.7.yml
.github/workflows/ci-moodle3.8.yml
.github/workflows/ci-moodle3.9.yml

ubuntu-18.04 image is deprecated and needs to be changed see https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

CI: change deprecated ubuntu runner image
