blindsidenetworks-ps/moodle-mod_bigbluebuttonbn

locallib.php
Hello, I was trying to check how compatible plugin with PHP7 and Moodle 3.1 and spotted this error. Looks like php7 and Moodle 3.1 are fine :) good job!
=> corrected call to the error reporting function

view.php
@jfederico requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/blindsidenetworks/moodle-mod_bigbluebuttonbn/
=> Scrutinizer Auto-Fixes

tests/behat/module_test_operational.feature
Added tests to check instance add, backup/restore, instance/course delete
=> GAO-447: Added Behat test to verify plugin operation

lib.php, locallib.php
Hi - we've noticed two issues, here's my (really) quick and mostly untested attempt at describing & fixing it.
=> Fix for typo and notification call.

tests/behat/recordings_only_instance.feature, tests/behat/room_only_instance.feature, tests/behat/room_with_recordings_instance.feature
Add behat tests to every one of the three instance types: room only, recordings only and room & recordings activities.
=> Add behat tests to every one of the three instance types.

bbb_broker.php, bbb_view.php, index.php, lib.php, locallib.php, tests/privacy_provider_test.php, view.php
Fixed issue with default settings for moderator are not applied to existent activities
=> Fix for CONTRIB-7437

CHANGES, RELEASENOTES
Reverts blindsidenetworks/moodle-mod_bigbluebuttonbn#65
=> Revert "v2.2.6: Updated CHANGES and RELEASENOTES before release"

classes/privacy/provider.php
v2.2.7: Removed overriden _get_contexts_for_userid from privacy
=> CONTRIB-7527 fixed

classes/privacy/provider.php
v2.2.7: Validate that user exist when processing privacy request
=> Fix for CONTRIB-7527

.travis.yml, locallib.php, tests/behat/recordings_import.feature, tests/generator/behat_mod_bigbluebuttonbn_generator.php, tests/generator/lib.php, tests/locallib_test.php, tests/privacy_provider_test.php, tests/recordings_test.php
* Recordings
* Rework on the privacy policy tests to use generator only
* Fix issue with travis build and behat tests by using chrome instead of firefox
=> CONTRIB-7982: Create additional Behat/Unit Test

lib.php, mod_form.php, tests/coverage.php, tests/lib_test.php
* Add a specific set of test to test each function from this library
* Add a coverage file specification (Moodle 3.7+)
* Fix a couple of errors /code styles detected by unit testing
=> CONTRIB-7970: only include or require the necessary files in lib.php

locallib.php
Prevent checksum error which return non reachable meeting.
=> Add utf8 support for substr for names

db/install.xml
Saved the install.xml file from the XMLDB editor to correctly format the files. 
Fixes a unit test on Totara.
=> Save install.xml with XMLDB

README.md
When installing this plugin it was a little unclear which version to grab past 3.0. I have added a table with information gathered from the plugin directory here: https://moodle.org/plugins/pluginversions.php?plugin=mod_bigbluebuttonbn
Closes #211
=> Issue #211: Updated Readme with branch table

locallib.php
Please see the commit messages for details
=> Bugfixes: Respect visibility of roles + "Moderator by default" setting was broken

lib.php
=> CONTRIB-8044: Do not declare new CFG variables if unit tests are running

db/install.xml
=> Fixed XMLSchema

bbb_broker.php, brokerlib.php, config-dist.php, lang/en/bigbluebuttonbn.php, locallib.php, mod_form.php
Fixes and updates to completion after bbbevents and scripts where updated
=> CONTRIB-7919: Fixes an updates to complete this feature

bbb_view.php, classes/external.php, classes/locallib/bigbluebutton.php, classes/locallib/mobileview.php, classes/output/mobile.php, db/services.php, mobile.notification.js, templates/mobile_view_notification.mustache, version.php, view.php
* Add a polling routine to display the join button when meeting is ready
* Refactor functions/methods related to building the bbbsession data
from the cmid
* Add new web service
=> CONTRIB-8162 mod_bigbluebuttonbn: If "Wait for moderator" is selected, we cannot join meeting.

lib.php, locallib.php
=> Added protection for empty cache values

db/install.xml
=> Fixed malformed index XML in install.xml

db/upgrade.php, version.php
=> Issue #290: Indexes incorrectly applied on master

composer.json
ADD support to composer/installers
=> UPDATE add extra property

locallib.php
Sort the list by alphabetical order,  so it is easier to find each element.
=> CONTRIB-8113 mod_bigbluebuttonbn: Users and roles in activity parameters should be sorted by Alphabetical order

locallib.php
Reverts blindsidenetworks/moodle-mod_bigbluebuttonbn#279
=> Revert "CONTRIB-8113 mod_bigbluebuttonbn: Users and roles in activity parameters should be sorted by Alphabetical order"

bbb_ajax.php
This has the effect of not redirecting the user if the login is invalid
and instead failing with an exception, as well as other performance
improvements.
=> bbb_ajax.php: define AJAX_SCRIPT

db/install.xml, db/upgrade.php, version.php
CONTRIB-8157: Added index for improving performance when querying logs
=> Fix #319 CONTRIB-8157: Added index for improving performance when querying logs

.gitignore, classes/locallib/config.php, classes/settings/renderer.php, lang/en/bigbluebuttonbn.php, locallib.php, mod_form.php, settings.php
- Add default welcome message to settings
- Replace HTML Editor with Textarea
- Set type to PARAM_Text
This code comes from PR #259 from @mikosche
=> CONTRIB-7845: Add default welcome message to settings

bbb_view.php, brokerlib.php, classes/external.php, classes/local/bbb_constants.php, classes/local/helpers/files.php, classes/local/helpers/instance.php, classes/local/helpers/logs.php, classes/local/helpers/reset.php, classes/locallib/config.php, classes/output/mobile.php, classes/privacy/provider.php, lib.php, locallib.php, tests/generator/lib.php, tests/helpers.php, tests/lib_test.php, tests/local/helpers/files_testcase.php, tests/local/helpers/instance_testcase.php, tests/local/helpers/logs_testcase.php, tests/local/helpers/reset_testcase.php, tests/privacy_provider_test.php, tests/recordings_test.php, viewlib.php
This is a change on which will be based the series of tickets linked to the MDL-70658 epic.
*  Move all non standard callback out of lib.php and in another namespace
* Update unit tests
* Removed deprecated lib callback
* Fixed a couple of coding issues (coding convention)
=> CONTRIB-8400: Inclusion of lib.php has side effects

classes/local/settings/settings.php, settings.php
Fix /admin/settings.php?section=modsettingbigbluebuttonbn page.
=> CONTRIB-8399: Fix admin/modules and admin/plugins pages

bbb_view.php, classes/locallib/bigbluebutton.php
* When used added the right parameter access was granted without a check
=> CONTRIB-8471: Fix issue with direct access to a group

lang/en/bigbluebuttonbn.php, locallib.php
* use PARAM_RAW instead of PARAM_TEXT
* fix language string typo in description
=> CONTRIB-8435: Welcome default (global) does not allow tags

lib.php
* Backport of the fix from 2.5 to 2.4-stable
=> CONTRIB-8461: Activity is always visible in calendar

lib.php
* Remove additional checks made for CONTRIB-7724 preventing the event to
show up if opening time > today
* Reorder the checks so we exit quickly if the room is not available
=> CONTRIB-7377: Activities are not listed in the upcoming event block

locallib.php
- Add moodle/course:view check so managers have now the list of all courses
=> CONTRIB-8489: Manager cannot see import links from all courses

locallib.php, tests/locallib_test.php
* In the BBB "Role assigned during live session" section, the roles and
users should be sorted alphabetically in the drop downs
=> CONTRIB-8113: Users and roles should be sorted alphabetically

bbb_broker.php, bbb_view.php, classes/local/bigbluebutton/recordings/recording.php, classes/local/bigbluebutton/recordings/recording_helper.php, classes/local/bigbluebutton/recordings/recording_proxy.php, classes/local/broker.php, classes/local/notifier.php, db/install.xml, db/upgrade.php, lang/en/bigbluebuttonbn.php, version.php
- Adapted code for working with new mdl_bigbluebuttonbn_recordings table
- Added more information to the message sent
=> CONTRIB-8628: Solved issues with recording ready notification

classes/test/testcase_helper_trait.php, tests/backup_restore_test.php, tests/completion_test.php, tests/lib_test.php, tests/local/bigbluebutton/recordings/recording_data_test.php, tests/local/helpers/files_test.php, tests/local/helpers/mod_helper_trait_test.php, tests/local/helpers/reset_test.php, tests/local/helpers/roles_test.php, tests/logger_test.php
* Backup/restore tests
* Use a trait instead of a superclass for tests
=> CONTRIB-8674: Write additional unit testing

classes/test/testcase_helper_trait.php, tests/backup_restore_test.php, tests/completion_test.php, tests/lib_test.php, tests/local/helpers/files_test.php, tests/local/helpers/mod_helper_trait_test.php, tests/local/helpers/reset_test.php, tests/local/helpers/roles_test.php, tests/logger_test.php, tests/recording_test.php
Fix issue noted in #449:
* Mainly code convention issues
* Refactor the trait
=> CONTRIB-8674: Fix coding style issues and test case helper trait

classes/external/get_recordings.php, classes/instance.php, classes/recording.php, classes/test/testcase_helper_trait.php, tests/backup_restore_test.php, tests/behat/recordings_import.feature, tests/recording_test.php
* Make sure we just do one backup/restore by test to speed up tests
* Fix issues with get_recording_for_course which did not exclude the
current activity
=> CONTRIB-8674: Fix issues with recordings and backup tests

classes/external/can_join.php, classes/external/end_meeting.php, classes/external/get_recordings.php, classes/external/meeting_info.php, classes/external/update_recording.php, classes/local/proxy/bigbluebutton_proxy.php, classes/privacy/provider.php, lang/en/bigbluebuttonbn.php, tests/backup_restore_test.php, tests/coverage.php, tests/external/can_join_test.php, tests/external/end_meeting_test.php, tests/generator/lib.php, tests/privacy/provider_test.php
This commit includes a number of commits related to fies for phpunit issues.
Some of these are found as part of the wider Moodle run as Moodle includes some unit tests which act as a sanity check for installed components.
=> 8660 phpunit fixes

classes/external/completion_validate.php, classes/external/get_recordings.php, classes/external/meeting_info.php, classes/external/update_recording.php, classes/test/testcase_helper_trait.php, lang/en/bigbluebuttonbn.php, tests/external/get_recordings_test.php
* Check that the API is working correctly
* Check different use case such as role/action, imported recordings...
=> CONTRIB-8674: Add first get_recording tests

classes/local/bigbluebutton/recordings/recording_data.php, classes/output/recording_row_actionbar.php, classes/output/recording_row_playback.php, classes/output/recording_row_preview.php, classes/output/renderer.php, templates/recording_row_actionbar.mustache, templates/recording_row_playback.mustache, templates/recording_row_preview.mustache
* Replace most HTML output by templates / renderables
* Fix issue with URL of presentation that should be hidden when unpublished
=> CONTRIB-8679: Replace recording data output by templates

classes/task/upgrade_imported_recordings.php, classes/task/upgrade_recordings.php, classes/test/testcase_helper_trait.php, tests/generator/lib.php, tests/task/upgrade_recordings_imported_test.php, tests/task/upgrade_recordings_test.php
* Add tests for recording upgrade
* Minor fixes (groupid and return value)
=> CONTRIB-8674: Add test for recording upgrade routine

tests/search_test.php
* Sanity check for searching the module (further tests will be added
later)
=> CONTRIB-8674: Add search test

classes/local/bigbluebutton/recordings/recording_data.php, classes/output/recording_row_preview.php, classes/test/testcase_helper_trait.php, tests/external/get_recordings_test.php, tests/generator/lib.php
* Recording preview is only set when recordings_preview is set to 1
=> CONTRIB-8674: Add tests for recording preview

classes/output/recording_row_playback.php, templates/recording_row_actionbar.mustache, templates/recording_row_playback.mustache, templates/recording_row_preview.mustache
* Remove the onclick event as it was not used (might be used later though)
=> CONTRIB-8694: Fix issue with recording playback (JS console)

classes/settings/renderer.php, lib.php, locallib.php
=> CONTRIB-8696: Prevent the shared_secret setting from being observed

classes/task/reset_recordings.php, mobileapp/mobile.notification.js, tests/external/can_join_test.php, tests/external/end_meeting_test.php, tests/external/get_bigbluebuttons_by_courses_test.php, tests/external/get_join_url_test.php, tests/external/get_recordings_test.php, tests/external/view_bigbluebuttonbn_test.php
These final changes make the phpdoc checks pass as much as possible.
=> MDL-70658: Address remaining CIBOT pickups

classes/local/proxy/proxy_base.php, classes/test/testcase_helper_trait.php, lib.php, tests/lib_test.php, tests/local/helpers/reset_test.php, tests/task/upgrade_recordings_imported_test.php, tests/task/upgrade_recordings_test.php
* Fix issue when ending a meeting and the TEST_MOD_BIGBLUEBUTTONBN_MOCK_SERVER is not defined
* Refactor upgrade recording tests
=> MDL-70658: Fix issues with PHP unit

classes/local/proxy/recording_proxy.php, classes/recording.php
It actually fixes 3 issues at once.
- We had a long lasting bug on fetch_recordings that makes up to 12 getRecordngs requests on each recording.
- We not only not show the ghost recordings when they are deleted outside Moodle, but also mark them as deleted so they are not fetched every time. It would have been an overhead in time (RECORDING_STATE_DELETED=5 state was added)
- We now make use of the cache_ttl setting we had not re-activated since the last big refactoring of recordings
Update 1:
In order to overcome the possibility of marking as deleted recordings when the BBB server is replaced we now also:
- use the filter getRecordings?state=any, so the deleted recordings are also returned
Update 2:
There is an edge case that occurs when the recording is hard-deleted and the activity …
=> CONTRIB-8777: restored synchrony of recordngs in Moodle and BBB

locallib.php
=> CONTRIB-8802: fix for overflow of getRecordings when breakout rooms are recorded

classes/test/testcase_helper_trait.php
This is a followu-up of CONTRIB-8773
=> MDL-73196: reverted change included by mistake (follow-up CONTRIB-8773)

lib.php
Fixed bigbluebuttonbn_logs 'has_recordings' value for meta column
=> CONTRIB-8922: Fixed bigbluebuttonbn_logs 'has_recordings' value for meta column

classes/local/config.php, db/upgrade.php, lang/en/bigbluebuttonbn.php
Reverts credentials back to default after upgrade
=> CONTRIB-8930

CHANGES, RELEASENOTES, version.php
*bumped up version
*  RELEASE NOTES and CHANGES
=> 2.4.6 RELEASE NOTES and CHANGES, bumped up version

mod_form.php
Added muteonstart_editable to show the field when needed.
=> CONTRIB-8939: added muteonstart_editable to show the field when needed

mod_form.php
Added missing muteonstart_editable in mod_form show block condition
=> CONTRIB-8941: Fix muteonstart not visible when muteonstart_editable is set

classes/output/recordings_session.php
* Logic to create 'Import recording links' button now includes importrecordings_enabled
=> CONTRIB-8949: Fix import recording links button

classes/local/proxy/recording_proxy.php, classes/recording.php
* fixed sort order in recording::fetch_records based on config settings
* removed recording_proxy::sort_recordings
=> CONTRIB-8967: Fix for recording sort

CHANGES, README.md, RELEASENOTES, version.php
=> 3.0-rc.2 RELEASE NOTES, README and CHANGES

classes/instance.php, classes/local/proxy/bigbluebutton_proxy.php, classes/meeting.php
* Role parameter added, moderatorPW and attendeePW and password will be removed in later versions.
=> CONTRIB-8983: Add role parameter

bbb_broker.php, classes/broker.php, classes/completion/custom_completion.php, classes/local/helpers/user_info.php, classes/local/proxy/bigbluebutton_proxy.php, classes/logger.php, classes/meeting.php, lang/en/bigbluebuttonbn.php, lib.php, mod_form.php, tests/behat/behat_mod_bigbluebuttonbn.php, tests/behat/completion.feature, tests/completion/completion_test.php, tests/generator/lib.php, tests/lib_test.php
* Backport of MDL-74468
*Completionattendance duration fixed
* Lang strings shortened
=> CONTRIB-9006: Backport of Custom Completion Fix

CHANGES, README.md, RELEASENOTES, version.php
=> 3.0-rc.4: RELEASE NOTES, README and CHANGES

classes/locallib/bigbluebutton.php, classes/locallib/config.php, classes/settings/validator.php, config-dist.php, lang/en/bigbluebuttonbn.php, lib.php, locallib.php
- add interface to select checksum algorithm
- set SHA1 as default
- add language strings
=> Enforce checksum algorithm

cli/migrate_recordings.php, db/upgrade.php
* CLI script to help migrate recordings on upgrade
* Check if DB recording field exist first before renaming
=> CONTRIB-9023: Backport of Upgrade script fix

classes/external/meeting_info.php, classes/instance.php, classes/meeting.php, lang/en/bigbluebuttonbn.php, templates/room_view.mustache, tests/instance_test.php, tests/meeting_test.php
* participantcount split up into moderatorcount + viewercount.
=> CONTRIB-9140: Fix userlimit

classes/locallib/config.php, classes/settings/renderer.php, config-dist.php, lang/en/bigbluebuttonbn.php, locallib.php, tests/behat/behat_mod_bigbluebuttonbn.php, tests/lib_test.php, viewlib.php
* Warning when test-install/test-moodle used
=> CONTRIB-9484: Backport registration code to v2.4
